image: node:10.15.3

stages:
  - install
  - build
  - release

cache:
  key: fcCache
  paths:
    - node_modules/

installModules:
  stage: install
  only:
    changes:
      - package.json
  tags:
    - docker
  script:
    - npm install --unsafe-perm
  cache:
    key: fcCache
    paths:
      - node_modules/
    policy: push

buildFC:
  stage: build
  only:
    changes:
      - package.json
  tags:
    - docker
  script:
    - npm run package
  cache:
    key: fcCache
    paths:
      - node_modules/
    policy: pull
  artifacts:
    name: '$CI_COMMIT_REF_SLUG'
    paths:
      - '*.vsix'

releaseFC:
  stage: release
  only:
    - master
  tags:
    - docker
  cache:
    key: fcCache
    paths:
      - node_modules/
    policy: pull
  script:
    - $(npm bin)/vsce publish -p $VSC_PUBKEY
