image: node:10.15.3

stages:
  - build
  - release

cache:
  key: fcCache
  untracked: true

buildFC:
  stage: build
  only:
    changes:
      - package.json
  tags:
    - docker
  script:
    - npm install --unsafe-perm
    - npm run package
  cache:
    key: fcCache
    untracked: true
  artifacts:
    name: '$CI_COMMIT_TITLE'
    paths:
      - '*.vsix'

releaseFC:
  stage: release
  only:
    refs:
      - master
    changes:
      - package.json
  tags:
    - docker
  cache:
    key: fcCache
    untracked: true
    policy: pull
  script:
    - $(npm bin)/vsce publish -p $VSC_PUBKEY
