image: node:10.15.3

stages:
  - test
  - build
  - release

cache:
  key: fcCache
  untracked: true

testFC:
  stage: test
  tags:
    - docker
  script:
    - npm install --unsafe-perm
    - /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - echo ">>> Started xvfb"
    - openssl aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD
    - echo ">>> Installing SFDX CLI"
    - npm install -g sfdx-cli
    - sfdx --version
    - sfdx plugins --core
    - sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME
    - echo ">>> Compiling"
    - npm run compile
    - echo ">>> Run integration test"
    - export SF_USERNAME=$SF_USERNAME
    - npm run test
  cache:
    key: fcCache
    untracked: true

buildFC:
  stage: build
  only:
    changes:
      - package.json
  tags:
    - docker
  script:
    - npm run package
  cache:
    key: fcCache
    untracked: true
  artifacts:
    name: '$CI_COMMIT_TITLE'
    paths:
      - '*.vsix'

releaseFC:
  stage: release
  only:
    refs:
      - master
    changes:
      - package.json
  tags:
    - docker
  cache:
    key: fcCache
    untracked: true
    policy: pull
  script:
    - $(npm bin)/vsce publish -p $VSC_PUBKEY
